const tree=document.querySelector("#tree"),gens=document.querySelector("#gens"),panel=document.querySelector("#panel"),overlay=document.querySelector("#overlay"),details=document.querySelector("#details");
const esc=s=>String(s??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;");
const initials=n=>n.trim().split(/\s+/).slice(0,2).map(x=>x[0]).join("").toUpperCase();

function levels(){const lv={},parents=new Set();Object.entries(family).forEach(([id,p])=>(p.parents||[]).forEach(x=>parents.add(id)));let roots=Object.keys(family).filter(id=>!(family[id].parents||[]).length);if(!roots.length)roots=[Object.keys(family)[0]];let q=roots.map(x=>[x,1]);while(q.length){let [id,l]=q.shift();if(!family[id]||(lv[id]&&lv[id]>=l))continue;lv[id]=l;(family[id].children||[]).forEach(c=>q.push([c,l+1]))}Object.keys(family).forEach(id=>lv[id]??=1);return lv}

function card(id){const p=family[id],b=document.createElement("button");b.className="card";b.innerHTML=`<div class="avatar">${initials(p.name)}</div><div class="name">${esc(p.name)}</div><div class="meta">${p.birth?"Born "+esc(p.birth):"Family member"}</div>`;b.onclick=()=>openPerson(id);return b}
function render(filter=""){tree.innerHTML="";let lv=levels(),max=Math.max(...Object.values(lv)),term=filter.toLowerCase();for(let l=1;l<=max;l++){let ids=Object.keys(family).filter(id=>lv[id]===l&&(!term||family[id].name.toLowerCase().includes(term)));if(!ids.length)continue;let row=document.createElement("div");row.className="row";row.dataset.label=`GENERATION ${l}`;ids.forEach(id=>row.appendChild(card(id)));tree.appendChild(row)}}
function renderGens(){gens.innerHTML="";let lv=levels(),max=Math.max(...Object.values(lv));for(let l=1;l<=max;l++){let ids=Object.keys(family).filter(id=>lv[id]===l),b=document.createElement("div");b.className="block";b.innerHTML=`<h3>Generation ${l}</h3>`;ids.forEach(id=>{let x=document.createElement("button");x.className="mini";x.textContent=family[id].name;x.onclick=()=>openPerson(id);b.appendChild(x)});gens.appendChild(b)}}
function openPerson(id){let p=family[id],sp=p.spouse&&family[p.spouse]?family[p.spouse].name:"—",pa=(p.parents||[]).filter(x=>family[x]).map(x=>family[x].name).join(", ")||"—",ch=(p.children||[]).filter(x=>family[x]).map(x=>family[x].name).join(", ")||"—";details.innerHTML=`<div class="detail"><div class="detailAvatar">${initials(p.name)}</div><h2>${esc(p.name)}</h2><div class="detailRow"><span class="label">Born</span>${esc(p.birth||"Not added")}</div><div class="detailRow"><span class="label">Spouse</span>${esc(sp)}</div><div class="detailRow"><span class="label">Parents</span>${esc(pa)}</div><div class="detailRow"><span class="label">Children</span>${esc(ch)}</div><div class="detailRow"><span class="label">About</span>${esc(p.notes||"Add notes in data.js")}</div></div>`;panel.classList.add("open");overlay.classList.add("open")}
function close(){panel.classList.remove("open");overlay.classList.remove("open")}
document.querySelector("#close").onclick=close;overlay.onclick=close;document.querySelector("#search").oninput=e=>render(e.target.value);
document.querySelector("#treeBtn").onclick=()=>{tree.classList.remove("hidden");gens.classList.add("hidden")};document.querySelector("#genBtn").onclick=()=>{tree.classList.add("hidden");gens.classList.remove("hidden");renderGens()};
render();renderGens();